apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-konflux-up-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: konflux_up_alerts
    interval: 1m
    rules:
    - alert: KonfluxAlert
      expr: (konflux_up offset 1h) unless on(service, check, source_cluster) konflux_up
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Availability metric 'konflux_up' is missing.
        description: >-
          Availability metric 'konflux_up' is missing some entries for check {{ $labels.check }}
          on service {{ $labels.service }} and cluster {{ $labels.source_cluster }} when compared
          to previous hour.
        alert_routing_key: 'o11y'
