apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-project-controller-availability-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: project-controller-availability
    interval: 1m
    rules:
    - alert: ProjectControllerDown
      expr: |
        konflux_up{
          namespace="project-controller",
          check="replicas-available",
          service="project-controller-controller-manager"
        } != 1
      for: 10m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          Project controller is down on cluster {{ $labels.source_cluster }}
        description: >
          Some of the replicas of {{ $labels.service }} are down on cluster
          {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S07NDQV6A4D>
        team: vanguard
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/vanguard/project-controller-down.md
