apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-image-controller-quay-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: image_controller_quay_alerts
      interval: 1m
      rules:
        - alert: QuayFailureAlert
          expr: (konflux_up{service="image-controller", check="quay"} offset 1h) unless on(service, check, source_cluster) konflux_up{service="image-controller", check="quay"}
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Availability metric 'konflux_up' is missing for {{ $labels.check }} in {{ $labels.service }}.
            description: >-
              The 'konflux_up' availability metric is missing for {{ $labels.check }} in {{ $labels.service }} on cluster {{ $labels.source_cluster }} indicating a possible service disruption.
            team: build
            alert_team_handle: <!subteam^S03DM1RL0TF>
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/image-controller/availability_quay.md
