apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-namespace-lister-alerting
  labels:
    tenant: rhtap

spec:
  groups:
  - name: namespace_lister_unavailable
    interval: 1m
    rules:
    - alert: NamespaceListerSynchronizationFailure
      expr: |
        increase(namespace_lister_accesscache_synch_op_total{status="failed"}[30m]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Namespace-lister cache has reported 2 synchronization failures in 30 minutes
        description: "Namespace-lister's cache on cluster '{{ $labels.source_cluster }}' has reported 2 synchronization failures in 30 minutes"
        alert_team_handle: <!subteam^S06G3MJT516>
        team: workspaces
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/namespace-lister/README.md
    - alert: NamespaceListerInternalError
      expr: increase(namespace_lister_api_counter{code="500"}[10m]) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Namespace-lister is reporting too many internal errors
        description: "Namespace-lister pod '{{ $labels.pod }}' on cluster '{{ $labels.source_cluster }}' is returning internal errors"
        alert_team_handle: <!subteam^S06G3MJT516>
        team: workspaces
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/namespace-lister/README.md
