# Metric format needed
# redhat_appstudio_integrationservice_global_github_app_available(service="integration-service-controller-manager-metrics-service") -> konflux_up(service="integration-service-controller-manager-metrics-service", check="github")
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-integration-service-availability
  labels:
    tenant: rhtap
spec:
  groups:
    - name: integration_service_github_availability
      interval: 1m
      rules:
        - record: konflux_up
          expr: label_replace(redhat_appstudio_integrationservice_global_github_app_available, "check", "github", "","")
