apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: git-url
        type: string
      - name: revision
        type: string
    workspaces:
      - name: workspace
    tasks:
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: workspace
        taskRef:
          bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
          name: git-clone
      - name: run-tests
        workspaces:
          - name: workspace
            workspace: workspace
        runAfter:
          - clone-repository
        taskSpec:
          workspaces:
            - name: workspace
          steps:
            - name: run-tests
              image: registry.access.redhat.com/ubi8/ubi:latest
              script: cd $(workspaces.workspace.path) && ./automation/test.sh
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
