name: Check Kubernetes YAMLs with kube-linter
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create ../results directory
        shell: bash
        run: mkdir -p ../results kustomizedfiles

      - name: Run kustomize build
        run: |
          for p in $(find config -name "*kustomization.y*l"); do kustomize build ${p%/*} -o kustomizedfiles/${p//\//-} || echo "^ ERROR when running kustomize build for ${p%/*} ^"; done

      - name: Scan yaml files with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        id: kube-linter-action-scan
        with:
          directory: kustomizedfiles
          format: plain
        continue-on-error: false
